### ISSUE TITLE
Confluent Hub

### ISSUE THREAD

**Issue by jasongriebeler** [marklogic-community/kafka-marklogic-connector#27]
Is there any ability to have this distributed on the confluent hub? Something like: https://www.confluent.io/hub/mongodb/kafka-connect-mongodb

Would make installation a bit easier.

Thanks!

-jason

**Comment by BillFarber** [comment]
I submitted the connector a few months ago and was contacted by a Confluent rep. I responded to his email and then sent a second response about a month ago to check on status, but I haven't heard back from him since.

I'll try again.

**Comment by jasongriebeler** [comment]
Thanks for the quick response. Fingers crossed it gets in. Since you're already on this, feel free to close this issue out unless you want to use it for tracking purposes.


thanks again.

**Comment by BillFarber** [comment]
The connector has now been published on the Confluent Hub: https://www.confluent.io/hub/marklogic/kafka-marklogic-connector
