### ISSUE TITLE
Allow for data to be ingested via a Data Services endpoint

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/kafka-marklogic-connector#3]
Data Services skips some overhead in the REST processing libraries in both the JVM process and MarkLogic, so will be faster. Since Kafka is Java-based, there's no need for the more generic REST/HTTP communication.

**Comment by damonfeldman** [comment]
However, leave the HTTP option in place for those who need it because they are using an older version of MarkLogic, or perhaps there is some HTTP handling oddness in their network or proxy infrastructure, such that they need to use current HTTP libs.

**Comment by rjrudin** [comment]
Yeah I think we'd support both connection types, with some properties applying to both and others being specific to one particular connection type.

**Comment by rjrudin** [comment]
This should be doable for 1.7.0. Can use an approach similar to that of the Spark connector, though I don't think we need to have a default DS endpoint installed - i.e. this will be for use cases where the REST API / DMSDK are too limiting and an ML user wants to provide their own DS endpoint to have full control over the writing process.

**Comment by rjrudin** [comment]
Resolved via #68
