### ISSUE TITLE
Kafka (ML Sink) - Support for AVRO and JSONConverter.

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic-community/kafka-marklogic-connector#32]
The only major drawback in using StringConverter is lack of schema registry support and message schema enforcement. 
 
Would be great if ML sink supported Avro or JsonConverter as both support schema registry.

**Comment by bgeorge11** [comment]
The changes for this has been identified. Working on this

**Comment by BillFarber** [comment]
This has been completed with #36
