### ISSUE TITLE
Capability for configuring URIs other than UUIDs

### ISSUE THREAD

**Issue by bgeorge111** [marklogic-community/kafka-marklogic-connector#35]
Have some configurable URI customisation strategies. Couples of ideas are 
1. URI from the value of the document in a JSON path
2. URI from the hash of the values from the document in a JSON path
3. URI from the Kafka meta data values (/<topic>/<partition>/<offset>) 

Notes: 
a) All the strategies should be for the uri parts between URIPrefix and URISuffix 
b) The uniqueness of the URI should be on the customer/administrator who configures the connector. If the URI is not unique, the connector will silently over-write the existing document.

**Comment by BillFarber** [comment]
This has been completed with #36 and is available in 1.4.0
