### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by aajacobs** [marklogic-community/kafka-marklogic-connector#37]
Version 1.2.1 from hub.confluent.io throws the following error upon initialization: `java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+`

Full error log:

```Sep 24 16:45:58 my.domain.com connect-distributed[29018]: [2020-09-24 16:45:58,578] INFO Kafka version: 5.5.0-ce (org.apache.kafka.common.utils.AppInfoParser:117)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: [2020-09-24 16:45:58,578] INFO Kafka commitId: dad78e2df6b714e3 (org.apache.kafka.common.utils.AppInfoParser:118)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: [2020-09-24 16:45:58,578] INFO Kafka startTimeMs: 1600980358578 (org.apache.kafka.common.utils.AppInfoParser:119)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: [2020-09-24 16:45:58,579] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1132)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: [2020-09-24 16:45:58,579] INFO [Consumer clientId=connector-consumer-testMarkLogic-0, groupId=connect-testMarkLogic] Subscribed to topic(s): test (org.apache.kafka.clients.consumer.KafkaConsumer:974)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: [2020-09-24 16:45:58,579] INFO Starting (com.marklogic.kafka.connect.sink.MarkLogicSinkTask:35)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: [2020-09-24 16:45:58,580] ERROR WorkerSinkTask{id=testMarkLogic-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:81)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:176)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:673)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: at com.marklogic.client.impl.OkHttpServices.connect(OkHttpServices.java:344)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: at com.marklogic.client.DatabaseClientFactory.newClient(DatabaseClientFactory.java:1218)

Sep 24 16:45:58 my.domain.com connect-distributed[29018]: at com.marklogic.client.ext.DefaultConfiguredDatabaseClientFactory.newDatabaseClient(DefaultConfiguredDatabaseClientFactory.java:76)```

**Comment by BillFarber** [comment]
Per Rob Rudin:
The project currently uses marklogic-data-hub:5.2.2 which uses ML Java Client 4.2, which runs on Java 8.
We need to upgrade to ML Java Client 5.3 which runs on Java 8 & 11.
So, the build.gradle will contain the following update:

    compile "com.marklogic:marklogic-client-api:5.3.0"    
    compile ("com.marklogic:marklogic-data-hub:5.2.4") {
        // Prefer the version above
        exclude module: "marklogic-client-api"
        
        // Excluding these because there's no need for them
        exclude module: "spring-boot-autoconfigure"
        exclude module: "spring-integration-http"
        exclude module: "jaeger-core"
        exclude module: "jaeger-thrift"
        // Excluding because it causes Kafka Connect to complain mightily if included
        exclude module: "logback-classic"
    }

Since we don’t expect breaking changes from an upgraded dependency, it would just be a minor version upgrade.
However, we should run “gradle dependencies > dep.txt” to see what the dependency tree looks like after making this change and compare it to the current dependency tree.

**Comment by BillFarber** [comment]
I attempted to replicate this issue using a Bitnami Kafka AMI (bitnami-kafka-2.6.0-0-r02-linux-debian-10) with OpenJDK 11.0.8. Surprisingly, the Connect client worked fine.

JAVA Version:
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.8+10-LTS, mixed mode)

Perhaps OpenJDK is ok with ML Java Client 4.2, but not Oracle Java. I'll try that next.

**Comment by BillFarber** [comment]
It also worked fine with Oracle's HotSpot Java.
JAVA Version:
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

**Comment by rjrudin** [comment]
Can verify this is not an issue, I've been running Confluent Platform locally on Java 11. To my knowledge, all of the dependencies of the connector run fine on both Java 8 and 11.
