### ISSUE TITLE
marklogic-sink.properties doesn't contain new security options properties

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic-community/kafka-marklogic-connector#38]
marklogic-sink.properties is missing something like:

```
ml.connection.enableCustomSsl=false
ml.connection.customSsl.hostNameVerifier=ANY
ml.connection.customSsl.tlsVersion=TLSv1
ml.connection.customSsl.mutualAuth=false
```

When I completed the Quick Start on the README, the command ``bin/connect-standalone.sh config/marklogic-connect-standalone.properties config/marklogic-sink.properties`` throws errors about those missing properties.

I could do a pull request to add those properties, if they are the correct defaults for the Quick Start to work. Or update the Quick Start instructions to include adding them?

**Comment by rjrudin** [comment]
Would be preferable if the connector runs fine without any optional properties specified. If a client doesn't need SSL, then a client shouldn't need any of those 4 properties in their properties file. That's true of all non-required connector properties.

**Comment by BillFarber** [comment]
I agree with Rob and I think it is work that I can prioritize to work on soon.

Andrew Jacobs (former ML, now of Confluent) is asking about this also. He listed out quite a few other properties that ought to be optional.

**Comment by BillFarber** [comment]
After thinking about this a little bit. Let's leave this issue as is:
Update the example marklogic-sink.properties to have default values for the properties mentioned by Stuart and also update the README.md file to include those properties.

However, I have also created a new issue (#41) to change the application to be able to handle missing optional properties.

**Comment by rjrudin** [comment]
Looks like #44 addressed this, so closing
