### ISSUE TITLE
Read data from ML via a source task

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/kafka-marklogic-connector#4]
Similar to the sink task we have already, should be straightforward to integrate a QueryBatcher into a Kafka source task - https://docs.confluent.io/current/connect/concepts.html#connect-tasks - so that data can be read from ML into a Kafka queue. 

The main point of interest is how a user can configure a query for the QueryBatcher to run. This should be very similar though to how the QueryMarkLogic NiFi processor works - just look at the different ways that a QueryBatcher can execute a query, and determine how to support each approach via Kafka properties.

**Comment by BillFarber** [comment]
I have created a branch with work on this: feature/kst-6-PrototypeSourceConnectorFromMarkLogic

I'm pretty happy with what a Source connector implementation (MarkLogicClientSourceTask) that uses the ML Java Client.
However, I struggled with the DMSDK version (MarkLogicDmsdkSourceTask). I need to work on this one a bit more.

**Comment by rjrudin** [comment]
We definitely need to use DMSDK here so that it can handle e.g. queries that match on millions of records or more.

The main design question then is - what kinds of queries can a user specify based on the constraints of a Kafka properties file? I mentioned the NiFi processor above because there's prior art here - take a look at QueryMarkLogic in the marklogic-nifi project - https://github.com/marklogic-community/marklogic-nifi-incubator/blob/9005cac8bab10246e6895d1f4c75fb76a9fd6a75/nifi-nar-bundles/nifi-marklogic-bundle/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/QueryMarkLogic.java#L446 . 

There's some reusable code there that should likely move to ml-javaclient-util or possibly even the ML Java client. That code knows how to take a query, expressed as a string, and a query type and then construct a QueryDefinition from it, and then call the appropriate dataMovementManager.newQueryBatcher method to construct a WriteBatcher. 

That processor also has support for a "state" query. That's a range-index-based query to narrow down the documents to query for. That's intended to avoid returning the same documents over and over. A typical use case is - find me everything since I last looked, which depends on a query on some dateTime value on the documents. 

I think for consistency with the NiFi processor, that's a better approach to support initially then adding every queried document to a collection, which introduces a lot of update overhead and possibly unwanted update transactions. That's something we could optionally support in the future, but it would not occur by default. 

Generally, I think most of QueryMarkLogic can be reproduced in a MarkLogicSourceTask. Duplicating the code is fine for now, that can be addressed later.
