### ISSUE TITLE
Code refactoring: Apply factory / strategy pattern  in handling additional formats. 

### ISSUE THREAD

**Issue by bgeorge111** [marklogic-community/kafka-marklogic-connector#40]
Apply factory / strategy pattern  in handling additional formats. Now, the DefaultSinkRecordConverter is handling all formats with if loops which can be made better in code maintenance by applying a strategy (or factory as it applies) pattern. This issue should not add / subtract any core features of the product and is only a tech debt.

**Comment by BillFarber** [comment]
1) DefaultSinkRecordConverter: Abstract the record converters in DSRC as implementations of a new ContentExtractor interface and using the factory and strategy patterns to select the correct implementation.

2) IOException in MarkLogicSinkTask, DocumentWriteOperationBuilder, DefaultSinkRecordConverter, and SinkRecordConverter: Is there a specific reason for adding the IOException handling? If not, it should be removed. Perhaps the error handler in MarkLogicSinkTask should just be a generic Exception handler?

**Comment by rjrudin** [comment]
This still looks like it's worth doing to simplify the complex `toContent(SinkRecord)` function in `DefaultSinkRecordConverter`. The intent is to take a `SinkRecord` and produce an `AbstractWriteHandle`, the latter being a required input for `DocumentWriteOperationImpl`. So perhaps an interface of:

```
interface AbstractWriteHandleBuilder {
  AbstractWriteHandle newHandle(SinkRecord);
  boolean supportsSinkRecord(SinkRecord);
}
```

`DefaultSinkRecordConverter` would then have a list of these builders. For a given `SinkRecord`, it would iterate over the list, calling `supportsSinkRecord` on each to find a match. If none is found, a handler for `StringHandle` would be used as as a default.

**Comment by rjrudin** [comment]
Going to hold off on this, we should get support for Data Services in place first and then revisit this. That's because we're not sure yet how we're going to convert the data in a `SinkRecord` into something that a Data Service endpoint is friendly with.

**Comment by rjrudin** [comment]
Closing this, as this is more likely to be done if/when we need to modify DefaultSinkRecordConverter.
