### ISSUE TITLE
Fix the application to not crash when optional properties are omitted from the config files.

### ISSUE THREAD

**Issue by BillFarber** [marklogic-community/kafka-marklogic-connector#41]
Currently, the application requires all the configuration properties to be listed in the config files. If a property is omitted, the system crashes.

We should refactor the code so that the system uses default and does not crash when non-required properties are not included in the config files.

**Comment by rjrudin** [comment]
Testing shows that this is working already. I think we can make this clear in the marklogic-sink file by commenting out everything but the bare minimum of properties. That will make it very clear the properties are optional so users aren't wondering if they need the property to be defined with an empty value.

**Comment by rjrudin** [comment]
Going to close this and expand the scope of #57
