### ISSUE TITLE
Temporal Support.

### ISSUE THREAD

**Issue by bgeorge111** [marklogic-community/kafka-marklogic-connector#50]
The connector should be able to write documents to temporal collections that are already created in the target database.

**Comment by rjrudin** [comment]
@bgeorge111 Have you tried doing this? Wondering what issue you ran into if you configured the collections parameter to use an already-existing temporal collection. I'll give it a try soon to see what happens and then if it doesn't work, we can figure out what additional configuration would be needed from the user.

**Comment by rjrudin** [comment]
Verified that this isn't yet supported. When I include a temporal collection in `ml.document.collections`, I get the following error:

```
Local message: failed to apply resource at documents: Bad Request. Server Message: TEMPORAL-COLLECTIONTEMPORAL
Cannot use temporal-collection in the collection parameter since it is a temporal collection
```

**Comment by rjrudin** [comment]
Looks like this will be straightforward to support - an example program:

```
    DocumentWriteOperationImpl writeOperation = new DocumentWriteOperationImpl(
                DocumentWriteOperation.OperationType.DOCUMENT_WRITE,
                "/test3.xml",
                new DocumentMetadataHandle().withCollections("other-collection"),
                content
        );

        DataMovementManager dmm = client.newDataMovementManager();
        WriteBatcher writeBatcher = dmm.newWriteBatcher().withTemporalCollection("temporal-collection");
        writeBatcher.add(writeOperation);
        writeBatcher.flushAndWait();
        dmm.stopJob(writeBatcher);
        client.release();
```

We'll likely want an `ml.document.temporalCollection` property that can then feed into `withTemporalCollection` as shown above.
