### ISSUE TITLE
Ability to apply transformation and data ingestion through custom Rest API endpoint

### ISSUE THREAD

**Issue by dixitsingla** [marklogic-community/kafka-marklogic-connector#56]
We have started exploring MarkLogic Kafka Connector and have few queries mentioned below.

- We store the data in ML in XML format whereas in Kafka the data is in Json. So is there any transformation mechanism/tool which allows us to convert the Json data to XML before sending to ML.
- As the data is stored in ML through our own API’s but we didn’t find any properties to handle the API endpoint path although there are properties to define the host and port.

**Comment by BillFarber** [comment]
Hello Dixit,

I think Lech already answered your first question by pointing to https://github.com/marklogic-community/kafka-marklogic-connector/tree/master/examples/dmsdk-transform, so I'll skip it for now.  If you have additional questions, let me know.

For the second question, there is no way to change the endpoint used by the Kafka connector. The connector uses MarkLogic's DMSDK and is intended to be used with a standard MarkLogic REST server. Therefore it can't be customized to a different endpoint.

**Comment by rjrudin** [comment]
@dixitsingla I just realized our README doesn't yet document the properties needed to using a transform with DMSDK; they are:

- ml.dmsdk.transform = the name of the REST transform to apply to each document
- ml.dmsdk.transformParams = comma-delimited string of param1,value1,param2,value2,etc

With those, you should be able to accomplish your goal of performing any transformation on each incoming message. If you already have a custom endpoint for transforming data, I recommend doing the following:

1. Move as much logic from that custom endpoint module into a reusable library module
2. Invoke that reusable library module from the REST transform that you identify via `ml.dmsdk.transform` above

**Comment by rjrudin** [comment]
I am closing this as I believe the combination of #57 (documenting the already-existing transform parameters) and #3 (allowing for a Data Services endpoint to be used) will fully address the need here. A Data Services endpoint will give an end user complete control over all aspects of document insertion.
