### ISSUE TITLE
Allow  the topic to  be added  as collections 

### ISSUE THREAD

**Issue by iowusu** [marklogic-community/kafka-marklogic-connector#7]
As a kafka-marklogic-connector user I will like to add to like to have the option to  the topics which the message was sent to as a collection name in MarkLogic.  

On marklogic_sink.properties I should be able to set TopicsAsCollection=true/false to allow the topic which the message sent on to be added to the MarkLogic collection name.

**Comment by iowusu** [comment]
Issue resolved

**Comment by BillFarber** [comment]
@iowusu Based on Rob's comments on the orginal PR (https://github.com/marklogic-community/kafka-marklogic-connector/pull/10), I reverted that merge. Please read through his notes and make changes to your branch accordingly.

@iowusu IMPORTANT - NOTE : When I reverted the PR merge, it looks like GitHub deleted your original branch. Please backup that branch locally and the push it to GitHub so you don't lose your original work.

Thanks,
Phil

**Comment by rjrudin** [comment]
@BillFarber  I think this can be closed, correct?
