### ISSUE TITLE
Bump the dependencies to use the latest version of Kafka (3.3.3)

### ISSUE THREAD

**Issue by BillFarber** [marklogic-community/kafka-marklogic-connector#86]
We need to get the connector up-to-date so that we can:
1.  verify that the connector works with the latest version
2. ensure we're using the latest bug and security fixes in the libraries
3. expand the connector functionality to use the latest Kafka features.

**Comment by rjrudin** [comment]
Run "./gradlew dependencies" after doing this to see if any conflicts exist between the ML Java Client and Kafka. I think you'll get one on the Jackson dependencies. It may be worth modifying the develop branch of this repo to depend on a 5.6.0-SNAPSHOT from the Java Client project (which a user would have to publish manually) while we wait for 5.6.0 to be released.

**Comment by BillFarber** [comment]
Bumped to Kafka 3.2.3 for compatibility with kafka-junit.
